#!/usr/bin/env python3
# Copyright 2026 The Zephyrus Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Emits bundled_keys_data.h from {"proxy_url": ..., "demo_token": ...}.

What ships in the browser is the address of the demo proxy and an expiring,
signed token for it. NOT a provider key: those live only in the proxy's
environment (see demo_proxy/), so extracting everything in the installer yields
nothing that works anywhere else, and only until the token expires.

This script refuses input that looks like a real provider key, so a mistake
cannot put one into a binary. The input file lives outside the source tree and
the output goes to the build directory; neither is ever committed.
"""
import argparse
import json
import os
import re
import secrets
import sys
from urllib.parse import urlparse

# Shapes of real provider keys. A demo token is "zd1.<digits>.<hex>".
REFUSED = (re.compile(r"^sk-"), re.compile(r"^AIza"), re.compile(r"^[0-9a-f]{32}$"))
TOKEN = re.compile(r"^zd1\.\d{1,12}\.[0-9a-f]{40}$")
# Both providers are reached through the proxy with the same token.
KINDS = ("anthropic", "assemblyai")


def arr(name, data):
    body = ", ".join(str(b) for b in data)
    return "inline constexpr std::array<uint8_t, %d> %s = {%s};\n" % (
        len(data), name, body)


def fail(message):
    sys.exit("gen_bundled_keys: " + message)


def load(path):
    with open(path, encoding="utf-8-sig") as f:  # PowerShell writes a BOM
        raw = json.load(f)
    unknown = [k for k in raw if not k.startswith("_") and
               k not in ("proxy_url", "demo_token")]
    if unknown:
        fail("unexpected field(s) %s; this file holds only proxy_url and "
             "demo_token. Provider keys do not go in the build." % unknown)
    token = str(raw.get("demo_token", "")).strip()
    url = str(raw.get("proxy_url", "")).strip().rstrip("/")
    if not token and not url:
        return "", ""
    if not token or not url:
        fail("proxy_url and demo_token must both be set")
    if any(p.search(token) for p in REFUSED) or not TOKEN.match(token):
        fail("demo_token is not a demo token (expected zd1.<expiry>.<sig>). "
             "If that is a provider key, it must NOT be put in the build.")
    parsed = urlparse(url)
    local = parsed.hostname in ("localhost", "127.0.0.1", "::1")
    if parsed.scheme != "https" and not (parsed.scheme == "http" and local):
        fail("proxy_url must be https (http only for localhost)")
    if parsed.username or parsed.password or parsed.query or parsed.fragment \
            or parsed.path not in ("", "/"):
        fail("proxy_url must be a bare origin such as https://name.vercel.app")
    return url, token


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--keys", default="")
    p.add_argument("--output", required=True)
    a = p.parse_args()

    url, token = load(a.keys) if a.keys else ("", "")

    out = ["// Generated by gen_bundled_keys.py. Do not edit, do not commit.\n",
           "#ifndef BUNDLED_KEYS_DATA_H_\n#define BUNDLED_KEYS_DATA_H_\n\n",
           "#include <array>\n#include <cstdint>\n#include <span>\n",
           "#include <string_view>\n\n",
           "namespace zephyrus::agent::bundled {\n\n"]
    out.append('inline constexpr std::string_view kProxyUrl = "%s";\n\n' % url)
    rows = []
    if token:
        for i, kind in enumerate(KINDS):
            data = token.encode("ascii")
            pad = secrets.token_bytes(len(data))
            out.append(arr("kPad%d" % i, pad))
            out.append(arr("kData%d" % i, bytes(b ^ q for b, q in zip(data, pad))))
            rows.append('    {"%s", kPad%d, kData%d},\n' % (kind, i, i))
    out.append("\nstruct Entry {\n  std::string_view kind;\n"
               "  std::span<const uint8_t> pad;\n"
               "  std::span<const uint8_t> data;\n};\n\n")
    if rows:
        out.append("inline constexpr Entry kEntries[] = {\n%s};\n" % "".join(rows))
    else:
        out.append("inline constexpr std::span<const Entry> kEntries;\n")
    out.append("\n}  // namespace zephyrus::agent::bundled\n\n#endif\n")

    os.makedirs(os.path.dirname(os.path.abspath(a.output)), exist_ok=True)
    with open(a.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(out))


if __name__ == "__main__":
    main()
