// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Pins the agreement between the C++ runtime hash and the Python converter.
//
// The browser hashes a request's host with base::PersistentHash and looks the
// result up in an artifact whose keys were produced by
// tools/build_entity_artifact.py. If the two implementations ever disagree by
// a single bit, EVERY lookup misses — and it fails silently: no crash, no
// error, the feature simply attributes nothing and the web looks clean. That
// is the worst possible failure mode for an accuracy-contract feature, so it
// gets a test rather than a comment.
//
// The expectations below were generated by the Python and are asserted against
// the C++. If this test fails, the two have diverged; regenerate with
// scratchpad genvec.py and find out which side moved. Do not "fix" it by
// updating the numbers without understanding why they changed —
// base::PersistentHash is documented as never changing because it is persisted
// to disk.

#include <stdint.h>

#include <string_view>

#include "base/hash/hash.h"
#include "chrome/browser/zephyrus/privacy/privacy_host_canon.h"
#include "testing/gtest/include/gtest/gtest.h"

namespace zephyrus_privacy {
namespace {

struct HashCase {
  std::string_view input;
  uint32_t expected;
};

TEST(EntityHashAgreementTest, PythonConverterMatchesPersistentHash) {
  // Generated by tools/build_entity_artifact.py's super_fast_hash().
  // Covers every tail length (len % 4 == 0..3), the empty string, real tracker
  // domains, punycode, and bytes >= 0x80 — the last of these matters because
  // SuperFastHash casts tail bytes through `signed char`, so they sign-extend.
  static constexpr HashCase kCases[] = {
      {"", 0u},
      {"a", 291415938u},
      {"ab", 1366002500u},
      {"abc", 3535673738u},
      {"abcd", 3671636187u},
      {"abcde", 1374488366u},
      {"doubleclick.net", 1432733664u},
      {"google-analytics.com", 1976779482u},
      {"facebook.net", 4099082279u},
      {"connect.facebook.net", 3925261792u},
      {"xn--80ak6aa92e.com", 371209927u},
      // Split literals on purpose: C++ hex escapes are greedy, so
      // "\xbcber" would consume b, b and e as hex digits and overflow.
      {"\xc3\xbc" "ber.de", 42378880u},
      {"\xff\xfe\x80" "test.com", 3658544124u},
      {"scorecardresearch.com", 1746703561u},
  };

  for (const HashCase& c : kCases) {
    EXPECT_EQ(c.expected, base::PersistentHash(c.input))
        << "hash disagreement for input of length " << c.input.size()
        << " (tail " << (c.input.size() % 4) << "): the Python converter and "
        << "base::PersistentHash have diverged, so every artifact lookup "
        << "would silently miss";
  }
}


// §9.7: the two sides must agree on WHAT gets hashed, not just on the hash.
//
// The converter reads arbitrary text out of a dataset -- mixed case, trailing
// dots, Unicode -- while the runtime only ever sees a GURL host, which is
// already lowercased and already punycode. Each pair below is one host spelled
// the way a dataset might spell it and the way the browser will actually see
// it; the expected value is what the Python produced for the DATASET spelling.
// If the runtime's canonicalisation of the browser spelling stops landing on
// the same number, non-ASCII or trailing-dot domains silently stop attributing.
struct CanonCase {
  std::string_view runtime_host;  // what GURL::host() gives us
  uint32_t expected;              // hash_domain() of the dataset's spelling
};

TEST(EntityHashAgreementTest, CanonicalisationAgreesAcrossBothSides) {
  static constexpr CanonCase kCases[] = {
      // Dataset "münchen.de" / "MÜNCHEN.DE" -> punycode, which is what the
      // browser requests.
      {"xn--mnchen-3ya.de", 3075739690u},
      // Dataset "例え.テスト" (Japanese IDN test TLD).
      {"xn--r8jz45g.xn--zckzah", 4194161687u},
      // Dataset "Example.COM." -- upper case AND a trailing dot.
      {"example.com", 1255502746u},
      // Dataset "doubleclick.net." and "DoubleClick.NET" both reduce here.
      {"doubleclick.net", 1432733664u},
  };

  for (const CanonCase& c : kCases) {
    EXPECT_EQ(c.expected,
              base::PersistentHash(CanonicalHostForHash(c.runtime_host)))
        << "canonicalisation drifted for " << c.runtime_host
        << "; the converter and the runtime would key this host differently "
           "and every lookup for it would miss silently";
  }
}

// The trailing dot has to survive the round trip through the runtime helper,
// because GURL does hand us fully-qualified names with one.
TEST(EntityHashAgreementTest, TrailingDotHashesAsTheBareHost) {
  EXPECT_EQ(base::PersistentHash(CanonicalHostForHash("doubleclick.net")),
            base::PersistentHash(CanonicalHostForHash("doubleclick.net.")));
}

}  // namespace
}  // namespace zephyrus_privacy
